/* @LICENSE(NICTA) */

/* This header was generated by kernel/tools/invocation_header_gen.py.
 *
 * To add an invocation call number, edit libsel4/include/interfaces/sel4.xml.
 *
 */
#ifndef __LIBSEL4_ARCH_INVOCATION_H
#define __LIBSEL4_ARCH_INVOCATION_H

enum arch_invocation_label {
    ARMPDClean_Data = nInvocationLabels + 0,
    ARMPDInvalidate_Data = nInvocationLabels + 1,
    ARMPDCleanInvalidate_Data = nInvocationLabels + 2,
    ARMPDUnify_Instruction = nInvocationLabels + 3,
    ARMPageTableMap = nInvocationLabels + 4,
    ARMPageTableUnmap = nInvocationLabels + 5,
    ARMPageMap = nInvocationLabels + 6,
    ARMPageUnmap = nInvocationLabels + 7,
    ARMPageClean_Data = nInvocationLabels + 8,
    ARMPageInvalidate_Data = nInvocationLabels + 9,
    ARMPageCleanInvalidate_Data = nInvocationLabels + 10,
    ARMPageUnify_Instruction = nInvocationLabels + 11,
    ARMPageGetAddress = nInvocationLabels + 12,
    nArchInvocationLabels
};

#endif /* __LIBSEL4_ARCH_INVOCATION_H */
