#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_SOS) += sos

sos-components-$(CONFIG_APP_SOSH) += sosh
sos-components-$(CONFIG_APP_TTY_TEST) += tty_test

sos-components-$(CONFIG_APP_PROXY1) += proxy1
sos-components-$(CONFIG_APP_PROXY) += proxy

sos-components-$(CONFIG_APP_PING) += ping
sos-components-$(CONFIG_APP_PONG) += pong

sos-components-$(CONFIG_APP_LPING) += lping
sos-components-$(CONFIG_APP_LPONG) += lpong


sos-components-$(CONFIG_APP_WEB) += web
sos-components-$(CONFIG_APP_TEMP_CONTROL) += temp_control


sos-components=$(addprefix $(STAGE_BASE)/bin/, $(sos-components-y))

sos: export COMPONENTS=${sos-components}
sos: ${sos-components-y} \
     libsel4 libelf $(libc) libcpio \
     libsel4cspace libserial libclock \
     liblwip libnfs libethdrivers \
     libsos libplatsupport
